#!/usr/bin/perl -w
# 
# Copyright (c) 2001-2003 Regents of the University of California. 
# All rights reserved.                                             
#
# See the file LICENSE included in this distribution for details.  
#
# $Id: genpage.pl,v 1.10 2005/07/01 17:45:46 srhea Exp $ 

use strict;
  
my $title = shift;
my $content_file = shift;
open (FILE, "$content_file") or die "Could not open $content_file";

print<<EOF;
<!-- 

  Copyright (c) 2001-2003 Regents of the University of California. 
  All rights reserved.                                             

  See the file LICENSE included in this distribution for details.  

EOF

print "  This file was automatically generated by genpage.pl.  To change it,\n";
print "  please edit the content file, $content_file.\n";
print "\n";
print "-->\n";
print "\n";
print "<title>The Bamboo DHT -- $title</title>\n";

print<<EOF;
<body    text="#000000" 
         link="#788f1d" 
        vlink="#875b25" 
        alink="#875b25" 
      bgcolor="#ffffff">

<table width="95%" border="0" width="100%" cellspacing="10">
<tr>

<!-- Left Column -->
<td width="30%" valign="top">
<img src="bamboo-logo.png" width="150" height="227" alt="(Bamboo graphic)">

<br> <b><a href="index.html">Introduction</a></b>

<br> <b><a href="news.html">News</a></b>

<br> <b><a href="search.html">Search</a></b>

<br> <b><a href="docs.html">Documentation</a></b>
     <ul> 
     <li> <a href="pubs.html">Publications</a>
     <li> <a href="faq.html">Frequently Asked Questions</a>
     <li> <a href="tutorial.html">Tutorial</a>
     <li> <a href="users-guide.html">User's Guide</a>
     <li> <a href="programmers-guide.html">Programmer's Guide</a>
     <li> <a href="cgi-bin/mailman/listinfo/bamboo-users">Mailing List</a>
     </ul>

<b><a href="license.html">License</a></b>
<br> <b><a href="download.html">Download</a></b>
<br> <b><a href="contrib.html">Contributors</a></b>
<br> <b><a href="contact.html">Contact Us</a></b>

</td>
<!-- End of Left Column -->

<!-- Right Column -->
<td align="left" valign="top">
<table width="100%" cellspacing="10">
<tr align="center"><td>

<p>
<p>
<big><big><b><font face="arial,helvetica,sanserif">The Bamboo Distributed
Hash Table</font></b></big></big>
<br>
<big><font face="arial,helvetica,sanserif">
A Robust, Open-Source DHT
</font></big>
<p>
</td></tr>

<tr><td bgcolor="#4a5f27">
        <font color="#ffffff" face="arial,helvetica,sanserif">
EOF

print "<big><strong>$title</strong></big>\n";

print<<EOF;
        </font>

      </td></tr>

<tr><td>

EOF

my $match = "\\\$" . "Id:.* (\\d\\d\\d\\d\\/\\d\\d\\/\\d\\d "
    . "\\d\\d:\\d\\d:\\d\\d) .*\\\$";

my $last_mod;
while (<FILE>) {
    
    if (m/$match/) {
        $last_mod = $1;
    }
    print;
}
close (FILE);

if (defined $last_mod) {
    print "<p><hr><em>Last modified $last_mod.</em>\n";
}

print<<EOF;

</tr></td>
</table>
</td>
<!-- End of Right Column -->

</tr>
</table>

</body>
</html>
EOF

