#!/bin/bash
#
# $Id: kill-it,v 1.1 2003/11/19 06:04:41 srhea Exp $
#

if [[ $# != 1 ]]
then 
    echo "usage: kill-it <port>"
    exit 1
fi

port=$1

cd /home/ucb8/srhea

if ! test -f pid-$port
then 
    echo "No node running on port $port"
    exit 1
fi 

kill -9 `cat pid-$port`
