bin/run-java bamboo.lss.DustDevil cfg/openhash_1.cfg &
bin/run-java bamboo.lss.DustDevil cfg/openhash_2.cfg &
bin/run-java bamboo.lss.DustDevil cfg/openhash_3.cfg &
bin/run-java bamboo.lss.DustDevil cfg/openhash_4.cfg &
bin/run-java bamboo.lss.DustDevil cfg/openhash_5.cfg &
bin/run-java bamboo.lss.DustDevil cfg/openhash_6.cfg &
bin/run-java bamboo.lss.DustDevil cfg/openhash_7.cfg &
bin/run-java bamboo.lss.DustDevil cfg/openhash_8.cfg &
bin/run-java bamboo.lss.DustDevil cfg/openhash_9.cfg &
bin/run-java bamboo.lss.DustDevil cfg/openhash_10.cfg &
