require 'sane'
require_relative 'header'
# too much data!
# VaryParameter.varyParameterAndRsync('vary_parameter/vr_largefile_no_prefetch_1_url_use_bittorrent_fromStart_falseby_AndMajorTimes_0_times_0.0666666666666667s__0s_30000000B_255000BPS_125000s_1.0s_2.0s_256000B', 'Using BitTorrent',[0,1],[["largefile_no_prefetch_1_url_use_bittorrent_atfalse_run1_of_4_major_1_of_1", "largefile_no_prefetch_1_url_use_bittorrent_atfalse_run2_of_4_major_1_of_1", "largefile_no_prefetch_1_url_use_bittorrent_atfalse_run3_of_4_major_1_of_1", "largefile_no_prefetch_1_url_use_bittorrent_atfalse_run4_of_4_major_1_of_1"], ["largefile_no_prefetch_1_url_use_bittorrent_atfalse_run1_of_4_major_1_of_1", "largefile_no_prefetch_1_url_use_bittorrent_atfalse_run2_of_4_major_1_of_1", "largefile_no_prefetch_1_url_use_bittorrent_atfalse_run3_of_4_major_1_of_1", "largefile_no_prefetch_1_url_use_bittorrent_atfalse_run4_of_4_major_1_of_1"]*2])


 MultipleRunsSameSettingGrapher.new(["largefile_no_prefetch_1_url_use_bittorrent_atfalse_run1_of_4_major_1_of_1", "largefile_no_prefetch_1_url_use_bittorrent_atfalse_run2_of_4_major_1_of_1", "largefile_no_prefetch_1_url_use_bittorrent_atfalse_run3_of_4_major_1_of_1", "largefile_no_prefetch_1_url_use_bittorrent_atfalse_run4_of_4_major_1_of_1"])
